name: file tree
 
on:
  workflow_dispatch:
jobs:
  file-tree:
    runs-on: self-hosted
    steps:
    - name: Install tree
      run: |
        sudo apt update
        sudo apt install tree
    - name: Execute tree
      run: time tree | tee filetreelist.txt
